OSOE-127: Upgrade to Orchard Core 1.4
Lombiq/Orchard-Base-Theme pull request #20
Opened 2022-06-05 18:17 UTC by DemeSzabolcs

OSOE-127

2022-06-06 19:57 UTC, DAud-IcI commented on Lombiq.BaseTheme.Tests.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        context.Exists(By.XPath("//form[@action = '/Login']/h1[contains(., 'Log in')]"));
I don't think the header level matters here so we can generalize:
```suggestion
        context.Exists(By.XPath("//form[@action = '/Login']/*[starts-with(name(), 'H' and [contains(., 'Log in')]"));
```

2022-06-06 19:59 UTC, DAud-IcI requested changes

2022-06-06 19:59 UTC, DAud-IcI commented on Lombiq.BaseTheme.Tests.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        context.Exists(By.XPath("//form[@action = '/Login']/h1[contains(., 'Log in')]"));
I don't think the header level matters here so we can generalize:
```suggestion
        context.Exists(By.XPath("//form[@action = '/Login']/*[starts-with(name(), 'H') and contains(., 'Log in')]"));
```

2022-06-07 10:57 UTC, sarahelsaig commented on Lombiq.BaseTheme.Tests.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        context.Exists(By.XPath("//form[@action = '/Login']/h1[contains(., 'Log in')]"));
fml it's `H` in Firefox but `h` in Chrome and I only checked in the dev console.

2022-06-07 11:00 UTC, merged