OSOE-548: Upgrade to Orchard Core 1.6 in Orchard-Base-Theme
Lombiq/Orchard-Base-Theme pull request #63
Opened 2023-04-25 18:25 UTC by Psichorex

[OSOE-548](https://lombiq.atlassian.net/browse/OSOE-548)

[OSOE-548]: https://lombiq.atlassian.net/browse/OSOE-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-28 17:19 UTC, Piedone approved these changes

2023-04-28 17:22 UTC, Piedone requested changes

2023-04-28 17:22 UTC, Piedone commented on Lombiq.BaseTheme/pnpm-lock.yaml
> -lockfileVersion: 5.4
See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/454#discussion_r1180648244

2023-04-28 18:24 UTC, Psichorex commented on Lombiq.BaseTheme/pnpm-lock.yaml
> -lockfileVersion: 5.4
Reverted

2023-05-01 19:30 UTC, Piedone approved these changes

2023-05-12 13:25 UTC, Piedone approved these changes

2023-05-21 20:28 UTC, Piedone approved these changes

2023-06-10 16:37 UTC, Piedone approved these changes

2023-06-10 18:23 UTC, Piedone reviewed
Just marking the merge from `issue/OSOE-641`.

2023-06-10 18:24 UTC, Piedone approved these changes

2023-06-18 23:13 UTC, merged