Fixing new C# 11 analyzer violations
Lombiq/Orchard-Base-Theme pull request #68
Opened 2023-06-04 19:49 UTC by Piedone

2023-06-05 14:29 UTC, 0liver requested changes

2023-06-05 14:29 UTC, 0liver commented on Lombiq.BaseTheme/Models/ZoneDescriptor.cs
> +            : string.Create(CultureInfo.InvariantCulture, $"layout{parent}__{id}");
This seems to be very verbose. Can't we have some shorter helper method in HL?

For example:
```c#
public static class StringCreator
{
    public static string Invariant(this DefaultInterpolatedStringHandler value) =>
        string.Create(CultureInfo.InvariantCulture, ref value);
}
```

Then this line would become:

```suggestion
            : StringCreator.Invariant($"layout{parent}__{id}");
```

2023-06-05 14:29 UTC, 0liver commented on Lombiq.BaseTheme/Models/ZoneDescriptor.cs
> +            : string.Create(CultureInfo.InvariantCulture, $"layout{parent}__{id}");
Or:
```suggestion
            : InvariantString.New($"layout{parent}__{id}");
```

2023-06-05 14:49 UTC, Piedone commented on Lombiq.BaseTheme/Models/ZoneDescriptor.cs
> +            : string.Create(CultureInfo.InvariantCulture, $"layout{parent}__{id}");
I looked into this but didn't try `DefaultInterpolatedStringHandler` (since you can't simply pass around `FormattableString`, simple approaches won't work), thanks.

2023-06-05 19:51 UTC, 0liver approved these changes

2023-06-06 11:22 UTC, 0liver approved these changes

2023-06-06 22:49 UTC, merged